name: "Gemini AI Code Reviewer"
description: "This GitHub Action automatically reviews PRs using Google's Gemini AI model."
author: 'truongnh1992'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  GEMINI_API_KEY:
    description: 'Google Gemini API key'
    required: true
  INPUT_EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
    INPUT_EXCLUDE: ${{ inputs.INPUT_EXCLUDE }}
branding:
  icon: "aperture"
  color: "green"